remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

logo: "images/Personal Favicon.png"

locale                   : "en-US"
title                    : "Brooke Moss"
title_separator          : "-"
subtitle                 : "Personal Site"
name                     : "Brooke Moss"
description              : "Photographer, Videographer, Programmer, Sustainable Engineer"
url                      : "https://www.brookem.dev"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "EarlJr53/earljr53.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/images/favicon.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
shortcut icon            : "/images/favicon.png"

markdown: "kramdown"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name             : "Brooke Moss"
  avatar           : "/images/enby.jpg"
  bio              : "Photographer, Videographer, Programmer, Sustainable Engineer"
  location         : "Western MA // Downeast Maine"
  email            : "connect@brookem.dev"
  links:
    - label        : "they/she"
      icon         : "fa-regular fa-fw fa-transgender"
      url          : "https://shetheypronounseducation.carrd.co"
    - label        : "Photography Portfolio"
      icon         : "fas fa-fw fa-camera"
      url          : "https://bearcove.media"
    - label        : "GitHub"
      icon         : "fab fa-fw fa-github"
      url          : "https://github.com/EarlJr53"
    - label        : "Twitter"
      icon         : "fab fa-fw fa-twitter-square"
      url          : "https://twitter.com/EarlJr7127"
    - label        : "Instagram"
      icon         : "fab fa-fw fa-instagram"
      url          : "https://instagram.com/bearcove.media"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/EarlJr7127"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/EarlJr53"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/bearcove.media"
      
defaults:
  - values:
      layout: single
      author_profile: true
      toc: true
      shortcut icon: "/images/favicon.png"

# Disables RSS feed icon
atom_feed:
  hide: true

# header:
#   show_overlay_excerpt: false
  

