remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

# logo: "icon.png"

locale                   : "en-US"
title                    : "Brooke Moss"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Brooke Moss"
description              : "Photographer, Videographer, Programmer, Sustainable Engineer"
url                      : "https://www.brookem.dev"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "EarlJr53/earljr53.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title

markdown: "kramdown"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name             : "Brooke Moss"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I am an **amazing** person."
  location         : "Western MA // Downeast Maine"
  email            : "connect@brookem.dev"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:connect@brookem.dev"
    - label: "Photography Portfolio"
      icon: "fas fa-fw fa-link"
      url: "https://bearcove.media"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/EarlJr7127"
#     - label: "Facebook"
#       icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/EarlJr53"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/bearcove.media"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/EarlJr7127"
#     - label: "Facebook"
#       icon: "fab fa-fw fa-facebook-square"
#       # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/EarlJr53"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/bearcove.media"
      
defaults:
  - values:
      layout: single

# Disables RSS feed icon
atom_feed:
  hide: true

header:
  show_overlay_excerpt: false
  

